import os

SENDLOOP_SUBDOMAIN = os.getenv("SENDLOOP_SUBDOMAIN")
assert SENDLOOP_SUBDOMAIN

SENDLOOP_API_KEY = os.getenv("SENDLOOP_API_KEY")
assert SENDLOOP_API_KEY

SENDLOOP_BASE_URL = "http://%s.sendloop.com/api/v3" % SENDLOOP_SUBDOMAIN

SENDLOOP_LIST_ID = os.getenv("SENDLOOP_LIST_ID")
assert SENDLOOP_LIST_ID
